# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dylan Xin
name: Dylan Xin
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dylanxin" # the subpath of your site, e.g. /blog
url: "https://nalydnix.github.io" # the base hostname & protocol for your site, e.g. http://example.com

atom_feed:
  hide: true

author:
  name: "Dylan Xin"
  avatar: /assets/images/profile_picture.jpg
  # avatar: "/assets/images/bio-photo.jpg"
  bio: "A regular software engineering student at UoA." # Note: Markdown is allowed
  location: "Auckland, New Zealand"
  links:
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/nalydnix"
    # - label: "Facebook"
    #   icon: "fab fa-fw fa-facebook"
    #   url: "https://www.facebook.com/profile.php?id=100008572926950"
    # - label: "Bilibili"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://space.bilibili.com/86775668"
    - label: "dylanxin@outlook.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dylanxin@outlook.com"

footer:
  links:
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/nalydnix"
    # - label: "Facebook"
    #   icon: "fab fa-fw fa-facebook"
    #   url: "https://www.facebook.com/profile.php?id=100008572926950"
    # - label: "Bilibili"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://space.bilibili.com/86775668"
    - label: "dylanxin@outlook.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dylanxin@outlook.com"

# Build settings
# theme: minima

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark"

search: true
search_full_content: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages
  - _posts
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
